services:
  - type: web
    name: zerotrustnet
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn --chdir backend app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0

